name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t storm69/storm69:latest
      - name: publish
        run: |
          docker login -u storm69 -p dckr_pat_7biXokKQCK2ej1LFaJYD-9v3vO4
          docker push storm69/storm69:latest
